export const urlConfig = {
    urlLogin: '/user/login',
    urlLogout: '/user/logout',
    urlSignup: '/user',
    urlForgotPassword: '/user/forgotPassword',
    urlValidateRecoveryCode: '/user/forgotPassword/validateToken',
    urlUser: '/user',
    urlCurrentUser: '/user/current',
    urlProduct: '/products/:id',
    urlProductCategorie: '/products/enum/categories',
    urlProductType: '/products/enum/types',
    urlProductUploadMedia: '/Product/uploadmedia',
    urlUploadMedia: '/media/uploadfile',
    urlGetImageByS3Name: '/Media/nameS3?nameS3=:nameS3',
    urlCheckout: '/checkouts/:id',
    urlOffer: '/offers/:id',
    urlCupom: '/coupons/:id',
    urlGetOfferByProductID: '/products/offers/:product_id',
    urlProductsToOrderBump: '/checkouts/order_bumps_to_checkout/:hash',
    urlCreateOrderBump: '/order_bumps/',
    urlDeleteOrderBump: '/order_bumps/:id',
    urlAbandonedCart: '',
    urlGetSales: '/payments/paid_payments',
    urlGetUnpaidSales: '/payments/unpaid_payments',
    urlViaCEP: 'https://viacep.com.br/ws/:cep/json/ ',
    urlBanks: '/bank/code_banks',
    urlAccountsBank: '/bank/accounts',
    urlDeleteAccountsBank: '/bank/delete_account',
    urlCreateAccountBank: '/bank/create_account',
    urlWithdrawHistory: '/withdraws/requests',
    urlRequestWithdraw: '/withdraws/request',
    urlRequestWithdrawInfos: '/withdraws/infos',
    urlToggleAccountBankStatus: '/bank/update_status',
    urlMembers: '/members/:id',
    urlDashboard: '/user/dashboard',
    urlCNPJWS: 'https://publica.cnpj.ws/cnpj/:cnpj',
    urlIBGEStates: 'https://servicodados.ibge.gov.br/api/v1/localidades/estados',
    urlCreateAccountCPF: '/kyc',
    urlCreateAccountCNPJ: '/payments/create_user_cnpj',
    urlModules: '/modules',
    urlUploadVideo: '/lessons/upload',
    urlUploadPreVideo: '/lessons/pre-url',
    urlUploadComplete: '/lessons/complete-upload',
    urlLessons: '/lessons',
    urlIntegration: '/integration',
    urlMembershipIntegrations: '/integration/:membership_id',
    urlMembershipOffers: '/integration/:membership_id/offers',
    urlDeleteMembershipOffers:
    '/integration/membership/:membership_id/offer/:offer_id',
}
